openapi: 3.0.0
info:
  title: Response API
  description: Reads response from database for the corresponding intent
  version: 1.0.0
servers:
  - url: 'localhost:3000/api'
paths:
  /response:
    post:
      summary: Get response for the predicted intents for a visitor message and bot
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                botId:
                  description: Identifier of bot
                  $ref: '#/components/schemas/MongoObjectId'
                  # Use the following example value for the challenge to yield results
                  example: 5f74865056d7bb000fcd39ff
                message:
                  type: string
                  description: The message to analyze for intent
                  example: Hello this is a chat message
              required:
                - botId
                - message
      responses:
        '200': # status code
          description: OK
          content:
            application/json:
              schema:
                type: string
        '400': # status code
          description: Bad Request
        '500': # status code
          description: Internal Server Error

components:
  schemas:
    MongoObjectId:
      type: string
      pattern: '/^[a-f\d]{24}$/i'
      example: 5f74865056d7bb000fcd39ff
